modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Daily%20Quests"
logoFile="icon.png"

[[mods]]
modId="dailyquests"
version="2.8"
displayName="Daily Quests"
displayURL="https://serilum.com/mod/daily-quests"
authors="Rick South"
description='''Complete randomly generated quests each day for experience and loot! Made for the 2024 CurseForge ModJam.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, aternosorg, Cherriesaurus, Linda Jansen, Michelle Smith, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.dailyquests]]
    modId="collective"
    type="required"
    versionRange="[8.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dailyquests]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "dailyquests.mixins.json"